// ============================================================
// Customer Signup Form - SIMPLE 4-FIELD registration
// ============================================================
// Requires: First Name, Email, NIC, Phone Number.
// Password is auto-generated so registration is fast.
// User completes their full profile after login.
// ============================================================

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/localization/l10n_ext.dart';
import '../../../core/theme/app_theme.dart';
import '../../legal/providers/terms_provider.dart';
import '../../legal/widgets/terms_acceptance_field.dart';
import '../providers/auth_provider.dart';
import '../../../main.dart';

class CustomerSignupForm extends StatefulWidget {
  /// Mirrors the Terms & Conditions tick up to the signup screen so
  /// Google sign-in can require it as well.
  final ValueChanged<bool>? onTermsChanged;

  const CustomerSignupForm({super.key, this.onTermsChanged});
  @override
  State<CustomerSignupForm> createState() => _CustomerSignupFormState();
}

class _CustomerSignupFormState extends State<CustomerSignupForm> {
  final _formKey = GlobalKey<FormState>();
  final _fName = TextEditingController();
  final _email = TextEditingController();
  final _nic = TextEditingController();
  final _phone = TextEditingController();

  // Terms & Conditions consent (required before the account can be created)
  bool _agreedToTerms = false;
  bool _showTermsError = false;

  /// Blocks the signup until the Terms & Conditions have been accepted.
  bool _termsAccepted() {
    if (_agreedToTerms) return true;
    setState(() => _showTermsError = true);
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(context.l10n.termsRequiredError),
        backgroundColor: context.statusColors.danger,
      ),
    );
    return false;
  }

  @override
  void dispose() {
    _fName.dispose();
    _email.dispose();
    _nic.dispose();
    _phone.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    if (!_termsAccepted()) return;
    final auth = context.read<AuthProvider>();

    // Send the essential fields — password auto-generated by backend
    final data = {
      'role': 'CUSTOMER',
      'firstName': _fName.text.trim(),
      'email': _email.text.trim(),
      'nic': _nic.text.trim(),
      'phone': _phone.text.trim(),
      // Consent recorded server-side against the version shown to the user
      'termsVersion': context.read<TermsProvider>().version,
      // Language the terms were actually read in (the viewer's pick, else
      // the app language)
      'termsLanguage':
          context.read<TermsProvider>().languageFor(Localizations.localeOf(context)),
    };

    final success = await auth.signup(data);
    if (!mounted) return;
    if (success) {
      // Profile is incomplete — user will be prompted to complete after login
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(context.l10n.accountCreatedCompleteProfile),
          backgroundColor: Theme.of(context).colorScheme.primary,
          duration: const Duration(seconds: 4),
        ),
      );
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (_) => const StartupScreen()),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(auth.error ?? context.l10n.registrationFailed)),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Info card explaining quick registration
          Container(
            padding: const EdgeInsets.all(12),
            margin: const EdgeInsets.only(bottom: 16),
            decoration: BoxDecoration(
              color: scheme.primaryContainer,
              borderRadius: BorderRadius.circular(AppRadius.card - 4),
            ),
            child: Row(
              children: [
                Icon(Icons.info_outline_rounded, color: scheme.onPrimaryContainer, size: 20),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    context.l10n.quickSignupInfo,
                    style: TextStyle(fontSize: 12, color: scheme.onPrimaryContainer),
                  ),
                ),
              ],
            ),
          ),

          // First Name
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _fName,
              textCapitalization: TextCapitalization.words,
              decoration: InputDecoration(
                labelText: context.l10n.firstName,
                prefixIcon: const Icon(Icons.person_rounded),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? context.l10n.firstNameRequired : null,
            ),
          ),

          // Email
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _email,
              keyboardType: TextInputType.emailAddress,
              decoration: InputDecoration(
                labelText: context.l10n.emailAddress,
                prefixIcon: const Icon(Icons.email_outlined),
              ),
              validator: (v) {
                if (v == null || v.isEmpty) return context.l10n.emailRequired;
                if (!v.contains('@') || !v.contains('.')) return context.l10n.validEmail;
                return null;
              },
            ),
          ),

          // NIC
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _nic,
              textCapitalization: TextCapitalization.characters,
              decoration: InputDecoration(
                labelText: context.l10n.nicNumber,
                prefixIcon: const Icon(Icons.badge_outlined),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? context.l10n.nicRequired : null,
            ),
          ),

          // Phone
          Padding(
            padding: const EdgeInsets.only(bottom: 24),
            child: TextFormField(
              controller: _phone,
              keyboardType: TextInputType.phone,
              decoration: InputDecoration(
                labelText: context.l10n.phoneNumber,
                prefixIcon: const Icon(Icons.phone_rounded),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? context.l10n.phoneRequired : null,
            ),
          ),

          // Register button
          // ---- Terms & Conditions (must be accepted to register) ----
          TermsAcceptanceField(
            onChanged: (agreed) {
              setState(() {
                _agreedToTerms = agreed;
                if (agreed) _showTermsError = false;
              });
              // Mirror the tick up to the signup screen (used by Google sign-in)
              widget.onTermsChanged?.call(agreed);
            },
            showError: _showTermsError,
          ),
          const SizedBox(height: 16),

          ElevatedButton.icon(
            onPressed: _submit,
            icon: const Icon(Icons.person_add_rounded),
            label: Text(
              context.l10n.registerAsCustomer,
              style: const TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }
}