// ============================================================
// Customer Signup Form - SIMPLE 4-FIELD registration
// ============================================================
// Requires: First Name, Email, NIC, Phone Number.
// Password is auto-generated so registration is fast.
// User completes their full profile after login.
// ============================================================

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/localization/l10n_ext.dart';
import '../providers/auth_provider.dart';
import '../../../features/home/screens/home_screen.dart';

class CustomerSignupForm extends StatefulWidget {
  const CustomerSignupForm({super.key});
  @override
  State<CustomerSignupForm> createState() => _CustomerSignupFormState();
}

class _CustomerSignupFormState extends State<CustomerSignupForm> {
  final _formKey = GlobalKey<FormState>();
  final _fName = TextEditingController();
  final _email = TextEditingController();
  final _nic = TextEditingController();
  final _phone = TextEditingController();

  @override
  void dispose() {
    _fName.dispose();
    _email.dispose();
    _nic.dispose();
    _phone.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    final auth = context.read<AuthProvider>();

    // Send the essential fields — password auto-generated by backend
    final data = {
      'role': 'CUSTOMER',
      'firstName': _fName.text.trim(),
      'email': _email.text.trim(),
      'nic': _nic.text.trim(),
      'phone': _phone.text.trim(),
    };

    final success = await auth.signup(data);
    if (!mounted) return;
    if (success) {
      // Profile is incomplete — user will be prompted to complete after login
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(context.l10n.accountCreatedCompleteProfile),
          backgroundColor: Colors.indigo,
          duration: const Duration(seconds: 4),
        ),
      );
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (_) => const HomeScreen()),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(auth.error ?? context.l10n.registrationFailed)),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Info card explaining quick registration
          Container(
            padding: const EdgeInsets.all(12),
            margin: const EdgeInsets.only(bottom: 16),
            decoration: BoxDecoration(
              color: Colors.indigo.shade50,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Colors.indigo.shade200),
            ),
            child: Row(
              children: [
                const Icon(Icons.info_outline, color: Colors.indigo, size: 20),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    context.l10n.quickSignupInfo,
                    style: const TextStyle(fontSize: 12, color: Colors.indigo),
                  ),
                ),
              ],
            ),
          ),

          // First Name
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _fName,
              textCapitalization: TextCapitalization.words,
              decoration: InputDecoration(
                labelText: context.l10n.firstName,
                prefixIcon: const Icon(Icons.person),
                border: const OutlineInputBorder(),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? context.l10n.firstNameRequired : null,
            ),
          ),

          // Email
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _email,
              keyboardType: TextInputType.emailAddress,
              decoration: InputDecoration(
                labelText: context.l10n.emailAddress,
                prefixIcon: const Icon(Icons.email_outlined),
                border: const OutlineInputBorder(),
              ),
              validator: (v) {
                if (v == null || v.isEmpty) return context.l10n.emailRequired;
                if (!v.contains('@') || !v.contains('.')) return context.l10n.validEmail;
                return null;
              },
            ),
          ),

          // NIC
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _nic,
              textCapitalization: TextCapitalization.characters,
              decoration: InputDecoration(
                labelText: context.l10n.nicNumber,
                prefixIcon: const Icon(Icons.badge_outlined),
                border: const OutlineInputBorder(),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? context.l10n.nicRequired : null,
            ),
          ),

          // Phone
          Padding(
            padding: const EdgeInsets.only(bottom: 24),
            child: TextFormField(
              controller: _phone,
              keyboardType: TextInputType.phone,
              decoration: InputDecoration(
                labelText: context.l10n.phoneNumber,
                prefixIcon: const Icon(Icons.phone),
                border: const OutlineInputBorder(),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? context.l10n.phoneRequired : null,
            ),
          ),

          // Register button
          ElevatedButton.icon(
            onPressed: _submit,
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(vertical: 14),
              backgroundColor: Colors.indigo,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10),
              ),
            ),
            icon: const Icon(Icons.person_add, color: Colors.white),
            label: Text(
              context.l10n.registerAsCustomer,
              style: const TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }
}